# Generated by Django 2.2.2 on 2019-06-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='paswword',
            new_name='password',
        ),
    ]
