# Generated by Django 2.2.2 on 2019-06-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Image',
        ),
    ]
