# Generated by Django 2.2.2 on 2019-06-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Image',
            field=models.ImageField(default=1, upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
